import type {
  DocumentMetadata,
  LinguisticMetrics,
  RiskFlag,
  ScoreBreakdown,
  FileType,
} from '../types/analysis'

// Herramientas IA conocidas
const AI_GENERATORS = [
  'chatgpt', 'openai', 'gpt', 'claude', 'gemini', 'copilot',
  'bard', 'llama', 'mistral', 'perplexity', 'writesonic',
  'jasper', 'copy.ai', 'rytr', 'quillbot', 'wordtune',
]

// Librerías de programación que generan documentos (muy sospechoso — indica creación automática)
const PROGRAMMING_LIBS = [
  // Python
  'python-docx', 'python_docx', 'reportlab', 'fpdf', 'fpdf2',
  'weasyprint', 'pdfkit', 'xhtml2pdf', 'pdfrw', 'pypdf',
  'sphinx', 'docutils', 'rst2pdf',
  // JavaScript/Node
  'pdfmake', 'jspdf', 'puppeteer', 'playwright', 'wkhtmltopdf',
  'html-pdf', 'pdf-lib', 'docx',
  // Java
  'itext', 'apache poi', 'flying saucer', 'openhtmltopdf',
  // General
  'pandoc', 'asciidoc', 'asciidoctor', 'latex', 'pdflatex',
  'xelatex', 'lualatex', 'context', 'wkhtmlto',
  // Genérico
  'script', 'automated', 'autogenerat', 'generated by',
]

// Procesadores de texto legítimos (reducen sospecha)
const WORD_PROCESSORS = [
  'microsoft word', 'ms word', 'libreoffice', 'openoffice',
  'apple pages', 'google docs', 'wps writer',
]

// Herramientas de conversión online (moderadamente sospechoso)
const ONLINE_CONVERTERS = [
  'ilovepdf', 'smallpdf', 'pdf24', 'pdfconvert',
  'online2pdf', 'sodapdf', 'sejda',
]

function flagIf(
  condition: boolean,
  flag: RiskFlag,
  flags: RiskFlag[]
): number {
  if (condition) {
    flags.push(flag)
    return flag.points
  }
  return 0
}

function dateDiffMinutes(a?: Date, b?: Date): number | undefined {
  if (!a || !b) return undefined
  return Math.abs(a.getTime() - b.getTime()) / 60000
}

export function calculateScore(
  metadata: DocumentMetadata,
  linguistic: LinguisticMetrics,
  fileType: FileType
): ScoreBreakdown {
  const flags: RiskFlag[] = []
  let metadataScore = 0
  let linguisticScore = 0
  let fingerprintScore = 0

  // =====================
  // METADATA (máx 40 pts)
  // =====================

  const wc = metadata.wordCount ?? linguistic.totalWords

  // 1. Tiempo de edición muy bajo respecto a palabras
  // Un humano escribe ~30-40 pal/min, edita/revisa mucho más despacio
  if (metadata.editingTimeMinutes !== undefined) {
    const wordsPerMin = wc / (metadata.editingTimeMinutes || 0.1)
    if (metadata.editingTimeMinutes < 1 && wc > 100) {
      metadataScore += flagIf(true, {
        id: 'edit_time_critical',
        category: 'metadata',
        severity: 'high',
        label: 'Tiempo de edición crítico',
        detail: `${metadata.editingTimeMinutes} min para ${wc} palabras (${wordsPerMin.toFixed(0)} pal/min). Generación instantánea — imposible para un humano.`,
        points: 20,
      }, flags)
    } else if (metadata.editingTimeMinutes < 3 && wc > 200) {
      metadataScore += flagIf(true, {
        id: 'edit_time_very_low',
        category: 'metadata',
        severity: 'high',
        label: 'Tiempo de edición muy bajo',
        detail: `${metadata.editingTimeMinutes} min para ${wc} palabras. Un humano tardaría al menos ~${Math.round(wc / 35)} min solo para escribir.`,
        points: 18,
      }, flags)
    } else if (metadata.editingTimeMinutes < 8 && wc > 300) {
      metadataScore += flagIf(true, {
        id: 'edit_time_low',
        category: 'metadata',
        severity: 'high',
        label: 'Tiempo de edición bajo',
        detail: `${metadata.editingTimeMinutes} min para ${wc} palabras. Muy poco tiempo para redactar y revisar este volumen.`,
        points: 12,
      }, flags)
    } else if (metadata.editingTimeMinutes < 15 && wc > 500) {
      metadataScore += flagIf(true, {
        id: 'edit_time_suspicious',
        category: 'metadata',
        severity: 'medium',
        label: 'Tiempo de edición sospechoso',
        detail: `${metadata.editingTimeMinutes} min para ${wc} palabras.`,
        points: 6,
      }, flags)
    }
  }

  // 2. Muy pocas revisiones (cada guardado en Word incrementa el contador)
  if (metadata.revisions !== undefined) {
    if (metadata.revisions === 0) {
      metadataScore += flagIf(true, {
        id: 'revisions_zero',
        category: 'metadata',
        severity: 'high',
        label: 'Cero revisiones registradas',
        detail: `0 revisiones. El documento nunca fue guardado iterativamente — indica creación automática de una sola vez.`,
        points: 15,
      }, flags)
    } else if (metadata.revisions === 1 && wc > 100) {
      metadataScore += flagIf(true, {
        id: 'revisions_one',
        category: 'metadata',
        severity: 'high',
        label: 'Sin revisiones iterativas',
        detail: `Solo 1 revisión. Documentos auténticos acumulan 5-20+ guardados durante la redacción.`,
        points: 12,
      }, flags)
    } else if (metadata.revisions <= 3 && wc > 300) {
      metadataScore += flagIf(true, {
        id: 'revisions_low',
        category: 'metadata',
        severity: 'medium',
        label: 'Muy pocas revisiones',
        detail: `${metadata.revisions} revisiones para ${wc} palabras. Sospechosamente pocas para este tamaño.`,
        points: 7,
      }, flags)
    } else if (metadata.revisions <= 5 && wc > 600) {
      metadataScore += flagIf(true, {
        id: 'revisions_medium',
        category: 'metadata',
        severity: 'low',
        label: 'Pocas revisiones para el tamaño del documento',
        detail: `${metadata.revisions} revisiones para ${wc} palabras.`,
        points: 3,
      }, flags)
    }
  }

  // 3. Fechas de creación y modificación muy cercanas
  const dateDiff = dateDiffMinutes(metadata.createdAt, metadata.modifiedAt)
  if (dateDiff !== undefined) {
    if (dateDiff < 1 && wc > 100) {
      metadataScore += flagIf(true, {
        id: 'dates_identical',
        category: 'metadata',
        severity: 'high',
        label: 'Creación y modificación simultáneas',
        detail: `Solo ${dateDiff.toFixed(1)} min de diferencia. El documento se creó y guardó en el mismo momento — coherente con generación automática.`,
        points: 12,
      }, flags)
    } else if (dateDiff < 5 && wc > 200) {
      metadataScore += flagIf(true, {
        id: 'dates_very_close',
        category: 'metadata',
        severity: 'high',
        label: 'Fechas de creación y modificación casi iguales',
        detail: `${dateDiff.toFixed(1)} min entre creación y modificación para ${wc} palabras. Un documento redactado humanamente acumula múltiples sesiones.`,
        points: 8,
      }, flags)
    } else if (dateDiff < 20 && wc > 400) {
      metadataScore += flagIf(true, {
        id: 'dates_close',
        category: 'metadata',
        severity: 'medium',
        label: 'Fechas cercanas para el tamaño del documento',
        detail: `${dateDiff.toFixed(1)} min de historial de edición para ${wc} palabras.`,
        points: 4,
      }, flags)
    }
  }

  // 4. Autor/creador vacío o genérico
  const authorStr = (metadata.author ?? '').toLowerCase().trim()
  const genericAuthors = ['unknown', 'user', 'admin', 'usuario', 'autor', 'author', 'owner']
  if (!authorStr) {
    metadataScore += flagIf(true, {
      id: 'no_author',
      category: 'metadata',
      severity: 'medium',
      label: 'Sin información de autoría',
      detail: 'Campo de autor vacío. Los documentos auténticos suelen contener el nombre real del usuario del sistema.',
      points: 7,
    }, flags)
  } else if (genericAuthors.includes(authorStr)) {
    metadataScore += flagIf(true, {
      id: 'generic_author',
      category: 'metadata',
      severity: 'medium',
      label: 'Autor genérico o placeholder',
      detail: `El autor figura como "${metadata.author}" — un valor genérico, no un nombre real.`,
      points: 5,
    }, flags)
  }

  metadataScore = Math.min(metadataScore, 40)

  // ========================
  // LINGÜÍSTICO (máx 40 pts)
  // ========================

  if (linguistic.totalWords >= 80) {
    // 1. Burstiness — varianza de longitud de frases
    // Investigación: humanos >10, IA tiende a 6-9
    if (linguistic.stdSentenceLength < 4 && linguistic.totalSentences >= 8) {
      linguisticScore += flagIf(true, {
        id: 'low_burstiness',
        category: 'linguistic',
        severity: 'high',
        label: 'Frases extremadamente uniformes',
        detail: `Desviación estándar: ${linguistic.stdSentenceLength.toFixed(1)} palabras. Los humanos muestran >10. Indica texto muy homogéneo, típico de IA.`,
        points: 12,
      }, flags)
    } else if (linguistic.stdSentenceLength < 7 && linguistic.totalSentences >= 8) {
      linguisticScore += flagIf(true, {
        id: 'medium_burstiness',
        category: 'linguistic',
        severity: 'high',
        label: 'Longitud de frases poco variable (burstiness bajo)',
        detail: `Desviación estándar: ${linguistic.stdSentenceLength.toFixed(1)} palabras. La escritura humana auténtica suele superar 10.`,
        points: 8,
      }, flags)
    } else if (linguistic.stdSentenceLength < 10 && linguistic.totalSentences >= 8) {
      linguisticScore += flagIf(true, {
        id: 'low_medium_burstiness',
        category: 'linguistic',
        severity: 'medium',
        label: 'Variabilidad de frases moderadamente baja',
        detail: `Desviación estándar: ${linguistic.stdSentenceLength.toFixed(1)} palabras.`,
        points: 4,
      }, flags)
    }

    // 2. TTR — riqueza léxica
    // Humanos en textos largos: 0.45-0.75; IA tiende a comprimir: 0.35-0.50
    if (linguistic.typeTokenRatio < 0.40) {
      linguisticScore += flagIf(true, {
        id: 'low_ttr',
        category: 'linguistic',
        severity: 'high',
        label: 'Vocabulario muy repetitivo',
        detail: `TTR: ${(linguistic.typeTokenRatio * 100).toFixed(1)}%. Por debajo del 40% indica pobreza léxica — texto generado tiende a reciclar palabras.`,
        points: 10,
      }, flags)
    } else if (linguistic.typeTokenRatio < 0.55) {
      linguisticScore += flagIf(true, {
        id: 'medium_ttr',
        category: 'linguistic',
        severity: 'medium',
        label: 'Riqueza léxica por debajo del rango humano',
        detail: `TTR: ${(linguistic.typeTokenRatio * 100).toFixed(1)}%. Texto humano auténtico típicamente supera el 55%.`,
        points: 5,
      }, flags)
    }

    // 3. Frases de transición típicas de IA
    if (linguistic.aiPhraseCount >= 4) {
      linguisticScore += flagIf(true, {
        id: 'ai_phrases_high',
        category: 'linguistic',
        severity: 'high',
        label: 'Muchas frases de transición típicas de IA',
        detail: `${linguistic.aiPhraseCount} frases detectadas: "${linguistic.aiPhrasesFound.slice(0, 5).join('", "')}"`,
        points: 12,
      }, flags)
    } else if (linguistic.aiPhraseCount >= 2) {
      linguisticScore += flagIf(true, {
        id: 'ai_phrases_medium',
        category: 'linguistic',
        severity: 'medium',
        label: 'Frases de transición IA presentes',
        detail: `${linguistic.aiPhraseCount} frases: "${linguistic.aiPhrasesFound.join('", "')}"`,
        points: 7,
      }, flags)
    } else if (linguistic.aiPhraseCount === 1) {
      linguisticScore += flagIf(true, {
        id: 'ai_phrases_low',
        category: 'linguistic',
        severity: 'low',
        label: 'Frase de transición IA detectada',
        detail: `"${linguistic.aiPhrasesFound[0]}"`,
        points: 3,
      }, flags)
    }

    // 4. Entropía Shannon — texto humano es más impredecible
    if (linguistic.shannonEntropy < 3.8 && linguistic.totalWords > 150) {
      linguisticScore += flagIf(true, {
        id: 'low_entropy',
        category: 'linguistic',
        severity: 'high',
        label: 'Entropía del texto muy baja',
        detail: `Entropía Shannon: ${linguistic.shannonEntropy.toFixed(2)} bits/carácter. Texto humano: 4.2-4.8 bits. Indica texto predecible y formulaico.`,
        points: 8,
      }, flags)
    } else if (linguistic.shannonEntropy < 4.3 && linguistic.totalWords > 200) {
      linguisticScore += flagIf(true, {
        id: 'medium_entropy',
        category: 'linguistic',
        severity: 'medium',
        label: 'Entropía del texto baja',
        detail: `Entropía Shannon: ${linguistic.shannonEntropy.toFixed(2)} bits/carácter. Por debajo del rango humano típico (4.2-4.8).`,
        points: 5,
      }, flags)
    }

    // 5. Párrafos muy uniformes
    if (linguistic.stdParagraphLength < 8 && linguistic.totalParagraphs >= 4) {
      linguisticScore += flagIf(true, {
        id: 'uniform_paragraphs',
        category: 'linguistic',
        severity: 'medium',
        label: 'Párrafos de longitud muy uniforme',
        detail: `Desviación estándar: ${linguistic.stdParagraphLength.toFixed(1)} palabras. La IA tiende a generar párrafos de tamaño muy similar entre sí.`,
        points: 6,
      }, flags)
    } else if (linguistic.stdParagraphLength < 15 && linguistic.totalParagraphs >= 6) {
      linguisticScore += flagIf(true, {
        id: 'medium_uniform_paragraphs',
        category: 'linguistic',
        severity: 'low',
        label: 'Párrafos moderadamente uniformes',
        detail: `Desviación estándar: ${linguistic.stdParagraphLength.toFixed(1)} palabras.`,
        points: 3,
      }, flags)
    }

    // 6. Slop phrases — patrones 1000x más frecuentes en IA (arXiv:2510.15061)
    if (linguistic.slopPhraseCount >= 5) {
      linguisticScore += flagIf(true, {
        id: 'slop_high',
        category: 'linguistic',
        severity: 'high',
        label: 'Muchos patrones "slop" de IA',
        detail: `${linguistic.slopPhraseCount} patrones detectados: "${linguistic.slopPhrasesFound.slice(0, 4).join('", "')}"… (ocurren 1000x más en IA que en humanos)`,
        points: 10,
      }, flags)
    } else if (linguistic.slopPhraseCount >= 2) {
      linguisticScore += flagIf(true, {
        id: 'slop_medium',
        category: 'linguistic',
        severity: 'medium',
        label: 'Patrones "slop" de IA presentes',
        detail: `${linguistic.slopPhraseCount} patrones: "${linguistic.slopPhrasesFound.join('", "')}"`,
        points: 5,
      }, flags)
    }

    // 7. Estilo impersonal — ausencia de pronombres de 1ª persona
    if (linguistic.pronounRatio < 0.3 && linguistic.totalWords > 200) {
      linguisticScore += flagIf(true, {
        id: 'no_pronouns',
        category: 'linguistic',
        severity: 'medium',
        label: 'Texto muy impersonal (sin pronombres de 1ª persona)',
        detail: `Solo ${linguistic.pronounRatio.toFixed(2)}% pronombres (yo, mi, nosotros…). La IA escribe sistemáticamente en 3ª persona o de forma impersonal.`,
        points: 6,
      }, flags)
    }

    // 8. Ausencia de preguntas — los humanos hacen preguntas; la IA casi nunca
    if (linguistic.questionRatio === 0 && linguistic.totalSentences >= 15) {
      linguisticScore += flagIf(true, {
        id: 'no_questions',
        category: 'linguistic',
        severity: 'low',
        label: 'Ninguna pregunta en el texto',
        detail: `0% de frases interrogativas en ${linguistic.totalSentences} frases. Los humanos en textos argumentativos incluyen preguntas retóricas.`,
        points: 4,
      }, flags)
    }

    // 9. Diversidad de primera palabra baja — la IA repite mucho los inicios de frase
    if (linguistic.firstWordDiversity < 0.4 && linguistic.totalSentences >= 10) {
      linguisticScore += flagIf(true, {
        id: 'low_first_word_diversity',
        category: 'linguistic',
        severity: 'medium',
        label: 'Inicios de frase muy repetitivos',
        detail: `Solo ${(linguistic.firstWordDiversity * 100).toFixed(0)}% de primeras palabras son únicas. La IA tiende a comenzar frases siempre igual.`,
        points: 6,
      }, flags)
    } else if (linguistic.firstWordDiversity < 0.55 && linguistic.totalSentences >= 10) {
      linguisticScore += flagIf(true, {
        id: 'medium_first_word_diversity',
        category: 'linguistic',
        severity: 'low',
        label: 'Moderada repetición en inicios de frase',
        detail: `${(linguistic.firstWordDiversity * 100).toFixed(0)}% de primeras palabras únicas.`,
        points: 3,
      }, flags)
    }

    // 10. Caracteres zero-width — posible marca de agua o manipulación
    if (linguistic.zeroWidthCharCount > 0) {
      linguisticScore += flagIf(true, {
        id: 'zero_width_chars',
        category: 'linguistic',
        severity: linguistic.zeroWidthCharCount > 5 ? 'high' : 'medium',
        label: 'Caracteres invisibles detectados',
        detail: `${linguistic.zeroWidthCharCount} carácter(es) de anchura cero (U+200B/C/D…). Posibles marcas de agua de IA, rastreo de origen o manipulación del texto.`,
        points: linguistic.zeroWidthCharCount > 5 ? 8 : 4,
      }, flags)
    }
  } else {
    flags.push({
      id: 'insufficient_text',
      category: 'linguistic',
      severity: 'low',
      label: 'Texto insuficiente para análisis lingüístico',
      detail: `Solo ${linguistic.totalWords} palabras extraídas. Se recomiendan al menos 80 para análisis fiable.`,
      points: 0,
    })
  }

  linguisticScore = Math.min(linguisticScore, 40)

  // =======================
  // HUELLAS (máx 20 pts)
  // =======================

  const genStr = (
    (metadata.generator ?? '') +
    ' ' +
    (metadata.creator ?? '') +
    ' ' +
    (metadata.producer ?? '')
  ).toLowerCase()

  // 1. Generador IA explícito en metadata — señal definitiva
  const foundAiGen = AI_GENERATORS.find((g) => genStr.includes(g))
  if (foundAiGen) {
    fingerprintScore += flagIf(true, {
      id: 'ai_generator',
      category: 'fingerprint',
      severity: 'high',
      label: 'Herramienta IA detectada en metadata',
      detail: `El campo de software contiene "${foundAiGen}". Creación directa con herramienta IA.`,
      points: 20,
    }, flags)
  }

  // 2. Librería de programación — el documento fue generado por código, no escrito
  const foundLib = PROGRAMMING_LIBS.find((lib) => genStr.includes(lib))
  if (foundLib && !AI_GENERATORS.some((a) => genStr.includes(a))) {
    fingerprintScore += flagIf(true, {
      id: 'programming_library',
      category: 'fingerprint',
      severity: 'high',
      label: 'Documento generado por librería de programación',
      detail: `Software detectado: "${foundLib}". El documento fue creado automáticamente por código — no redactado manualmente. Alta correlación con contenido generado por IA.`,
      points: 15,
    }, flags)
  }

  // 3. Sin rsid en DOCX (Word no fue usado para escribirlo)
  if (fileType === 'docx' && metadata.hasRevisionIds === false) {
    fingerprintScore += flagIf(true, {
      id: 'no_rsid',
      category: 'fingerprint',
      severity: 'medium',
      label: 'Sin IDs de revisión Word (rsid)',
      detail: 'Microsoft Word inserta rsid en cada párrafo al guardar. Su ausencia indica que el DOCX fue generado programáticamente, no escrito en Word.',
      points: 8,
    }, flags)
  }

  // 4. Herramienta de conversión online
  const foundConverter = ONLINE_CONVERTERS.find((c) => genStr.includes(c))
  if (foundConverter) {
    fingerprintScore += flagIf(true, {
      id: 'converter_tool',
      category: 'fingerprint',
      severity: 'medium',
      label: 'Creado con conversor online',
      detail: `"${metadata.producer ?? metadata.creator ?? metadata.generator}" es un servicio de conversión. El original pudo ser generado por IA y luego convertido para ocultar la fuente.`,
      points: 6,
    }, flags)
  }

  // 5. Fuentes tipográficas múltiples — señal de copia-pega entre documentos
  if (metadata.fontFamilyCount !== undefined) {
    if (metadata.fontFamilyCount > 6) {
      fingerprintScore += flagIf(true, {
        id: 'many_fonts',
        category: 'fingerprint',
        severity: 'high',
        label: 'Muchas fuentes tipográficas diferentes',
        detail: `${metadata.fontFamilyCount} fuentes distintas: ${(metadata.fontFamilies ?? []).slice(0, 5).join(', ')}… Fuerte indicador de copia-pega desde múltiples documentos.`,
        points: 10,
      }, flags)
    } else if (metadata.fontFamilyCount > 3) {
      fingerprintScore += flagIf(true, {
        id: 'several_fonts',
        category: 'fingerprint',
        severity: 'medium',
        label: 'Varias fuentes tipográficas',
        detail: `${metadata.fontFamilyCount} fuentes: ${(metadata.fontFamilies ?? []).join(', ')}. Puede indicar texto pegado de distintas fuentes.`,
        points: 5,
      }, flags)
    }
  }

  fingerprintScore = Math.min(fingerprintScore, 20)

  const total = metadataScore + linguisticScore + fingerprintScore

  // Umbrales más estrictos: 20/40/65 en lugar de 25/50/75
  let level: ScoreBreakdown['level']
  let levelLabel: string
  if (total <= 20) {
    level = 'low'
    levelLabel = 'Riesgo bajo — apariencia de documento auténtico'
  } else if (total <= 40) {
    level = 'moderate'
    levelLabel = 'Riesgo moderado — varios indicadores sospechosos'
  } else if (total <= 65) {
    level = 'high'
    levelLabel = 'Riesgo alto — probable uso de IA o contenido copiado'
  } else {
    level = 'critical'
    levelLabel = 'Riesgo muy alto — fuerte evidencia de IA / generación automática'
  }

  return {
    metadataScore,
    linguisticScore,
    fingerprintScore,
    total,
    level,
    levelLabel,
    flags,
  }
}
